hex: all
	avr-objcopy -O ihex -R .eeprom Aquaduino-Next.elf Aquaduino-Next.hex
	
objdump: all
	avr-objdump -S Aquaduino-Next.elf > AquduinoMain.dump
	
size: all
	avr-size Aquaduino-Next.elf

	
upload: hex
	avrdude -C../avrdude.conf -patmega2560 -cwiring -P$(ARDUINOCOM) -b115200 -D -Uflash:w:Aquaduino-Next.hex:i 